sandbook/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('base', include('base.urls', namespace='base')),
    path('admin-dj/', admin.site.urls),
    path('admin-mgt/', include('operation.urls', namespace='operation')),
    path('', include('portal.urls', namespace='portal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sandbook/base/models/novel.py
import os
import re
import time

from django.core.files.storage import FileSystemStorage
from django.db import models

from base.constants.novel import (
    DEFAULT_COVER, NOVEL_STATUS_UNAPPROVED, NOVEL_STATUS_ACTIVE, NOVEL_STATUS_FINISHED,
    NOVEL_STATUS_BLOCKED
)
from django.core.cache import cache

from general.utils.text import get_filename_extension, calc_word_count


class CategoryMixin:

    @property
    def novel_count_key(self):
        raise NotImplementedError

    def novel_count(self):
        return cache.get(self.novel_count_key)


class Category(CategoryMixin, models.Model):
    """
    一级分类
    """
    name = models.CharField('名称', max_length=32)
    description = models.CharField('描述', max_length=255)

    class Meta:
        db_table = 'base_novel_category'

    def __str__(self):
        return self.name

    @property
    def novel_count_key(self):
        return 'sc_%d_count' % self.id


class SubCategory(CategoryMixin, models.Model):
    """
    二级分类
    """
    name = models.CharField('名称', max_length=32)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='一级分类')
    description = models.CharField('描述', max_length=255)

    class Meta:
        db_table = 'base_novel_sub_category'
        default_permissions = ()

    def __str__(self):
        return self.name

    @property
    def novel_count_key(self):
        return 'c_%d_count' % self.id

    def incr_novel_count(self, count: int):
        """
        count 可以为正负整数
        """
        cache.incr(self.novel_count_key, count)


def cover_path(instance, filename):
    new_name = '%s.%s' % (str(int(time.time())), get_filename_extension(filename))
    return os.path.join('novel', 'cover', str(instance.author_id), new_name)


class Novel(models.Model):
    """
    小说
    """
    STATUS = {
        'unapproved': NOVEL_STATUS_UNAPPROVED,
        'active': NOVEL_STATUS_ACTIVE,
        'finished': NOVEL_STATUS_FINISHED,
        'blocked': NOVEL_STATUS_BLOCKED,
    }
    STATUS_CHOICES = (
        (STATUS['unapproved'], '未审核'),
        (STATUS['active'], '连载中'),
        (STATUS['finished'], '已完结'),
        (STATUS['blocked'], '已屏蔽')
    )
    name = models.CharField('书名', unique=True, max_length=64)  # TODO: 书名验证
    author = models.ForeignKey('base.User', on_delete=models.SET_NULL, null=True, verbose_name='作者')
    intro = models.TextField('简介', max_length=1024)
    status = models.SmallIntegerField('状态', choices=STATUS_CHOICES, default=NOVEL_STATUS_UNAPPROVED)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name='一级分类')
    sub_category = models.ForeignKey(SubCategory, on_delete=models.SET_NULL, null=True, verbose_name='二级分类')
    cover = models.ImageField(
        '封面', storage=FileSystemStorage(), default=DEFAULT_COVER,
        upload_to=cover_path, blank=True
    )
    word_count = models.PositiveIntegerField('字数', default=0)
    created_at = models.DateTimeField('创建于', auto_now_add=True)
    updated_at = models.DateTimeField('更新于', auto_now=True)

    class Meta:
        db_table = 'base_novel'
        ordering = ('-id',)
        default_permissions = ()
        permissions = (
            ('view_novel', '查看小说'),
            ('create_novel', '创建小说'),
            ('change_novel', '更改小说'),
            ('delete_novel', '删除小说'),
            ('finish_novel', '完结小说'),
            ('block_novel', '屏蔽小说'),
            ('verify_novel', '审核小说')
        )


class NovelComment(models.Model):
    """
    书评
    """
    novel = models.ForeignKey(Novel, on_delete=models.CASCADE, verbose_name='小说', related_name='comments', )
    user = models.ForeignKey('base.User', on_delete=models.SET_NULL, null=True, verbose_name='用户',
                             related_name='nc_user')
    title = models.CharField('标题', max_length=32, blank=True)  # 标题可选
    content = models.CharField('内容', max_length=4096)
    created_at = models.DateTimeField('创建于', auto_now_add=True)

    class Meta:
        db_table = 'base_novel_comment'
        default_permissions = ()


class NovelCommentReply(models.Model):
    """
    书评回复
    """
    comment = models.ForeignKey(NovelComment, on_delete=models.CASCADE, related_name='replies',
                                verbose_name='书评')
    content = models.CharField('内容', max_length=1024)
    user = models.ForeignKey('base.User', on_delete=models.SET_NULL, null=True,
                             related_name='nc_reply_user', verbose_name='回复用户')
    created_at = models.DateTimeField('创建于', auto_now_add=True)

    class Meta:
        db_table = 'base_novel_comment_reply'
        default_permissions = ()


class Volume(models.Model):
    """
    卷
    """
    name = models.CharField('卷名', max_length=32, default='正文卷')
    novel = models.ForeignKey(Novel, on_delete=models.CASCADE, verbose_name='小说')
    created_at = models.DateTimeField('创建于', auto_now_add=True)

    class Meta:
        db_table = 'base_novel_volume'
        default_permissions = ()


class Chapter(models.Model):
    """
    章节
    """
    STATUS = {
        'saved': 0,
        'submitted': 1,
        'blocked': 2,
        'approved': 3  # 暂不用
    }
    STATUS_CHOICES = (
        (STATUS['saved'], '已保存'),
        (STATUS['submitted'], '已提交'),
        (STATUS['blocked'], '已屏蔽'),
        (STATUS['approved'], '已审核')
    )

    title = models.CharField('标题', max_length=32, blank=True, default='新章节')  # TODO: 章节名验证
    content = models.TextField('内容', max_length=65535, blank=True)
    volume = models.ForeignKey(Volume, on_delete=models.CASCADE, verbose_name='卷')
    word_count = models.PositiveIntegerField('字数', default=0)
    is_free = models.BooleanField('免费', default=True)
    status = models.IntegerField('状态', choices=STATUS_CHOICES, default=STATUS['saved'])
    created_at = models.DateTimeField('创建于', auto_now_add=True)
    updated_at = models.DateTimeField('更新于', auto_now=True)

    class Meta:
        db_table = 'base_novel_chapter'
        default_permissions = ()


# class ChapterUpdated(models.Model):
#     ...


class Paragraph(models.Model):
    """
    段落
    """
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE, verbose_name='章节')
    content = models.TextField('内容', max_length=65535)  # TODO: 段落字数限制
    serial = models.PositiveIntegerField('序号', default=1)

    class Meta:
        db_table = 'base_novel_paragraph'
        default_permissions = ()
        unique_together = (('chapter', 'serial'),)

    @property
    def word_count(self):
        return calc_word_count(self.content)


class ParagraphComment(models.Model):
    """
    段评
    """
    paragraph = models.ForeignKey(Paragraph, on_delete=models.CASCADE, verbose_name='段落')
    user = models.ForeignKey('base.User', on_delete=models.SET_NULL, null=True, verbose_name='用户')
    content = models.CharField('内容', max_length=1024)
    created_at = models.DateTimeField('创建于', auto_now_add=True)

    class Meta:
        db_table = 'base_novel_paragraph_comment'
        default_permissions = ()


class ParagraphCommentReply(models.Model):
    """
    段评回复
    """
    paragraph_comment = models.ForeignKey(ParagraphComment, on_delete=models.CASCADE, verbose_name='段评')
    user = models.ForeignKey('base.User', on_delete=models.SET_NULL, null=True,
                             related_name='pc_reply_user', verbose_name='回复用户')
    created_at = models.DateTimeField('创建于', auto_now_add=True)

    class Meta:
        db_table = 'base_novel_paragraph_comment_reply'
        default_permissions = ()

sandbook/portal/models.py
from django.db import models

# Create your models here.



# class Settings()

sandbook/portal/views/account.py
from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ValidationError, PermissionDenied
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView, FormView, DetailView, View

from base.models.account import User
from general.forms.mixin import FormValidationMixin, JSONResponseMixin
from portal.forms.account import AuthenticationForm, SignUpForm, ActiveForm, PasswordResetForm, SetPasswordForm
from portal.tasks import send_user_creating_email

INTERNAL_ACTIVE_URL_TOKEN = 'account-active'
INTERNAL_ACTIVE_SESSION_TOKEN = '_account_active_token'


class IsLogin(JSONResponseMixin, View):

    def get(self, request, *args, **kwargs):
        result = True if request.user.is_authenticated else False
        return self.json_response(result=result)


class Login(FormValidationMixin, auth_views.LoginView):
    authentication_form = AuthenticationForm
    template_name = 'portal/account/login.html'
    redirect_authenticated_user = True


class Logout(auth_views.LogoutView):
    pass


class SignUp(FormValidationMixin, CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'portal/account/signup.html'
    success_url = reverse_lazy('portal:account_signup_done')

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        response = super().form_valid(form)
        # site = get_current_site(self.request)
        # send email to user
        send_user_creating_email.delay(
            [self.object.email],
            self.object.username,
            self.request.build_absolute_uri(
                reverse(
                    'portal:account_active',
                    kwargs={
                        'uidb64': urlsafe_base64_encode(force_bytes(self.object.pk)),
                        'token': default_token_generator.make_token(self.object)
                    }
                )
            ),
        )
        return response


class Active(FormView):
    valid_link = False
    user = None
    token_generator = default_token_generator
    form_class = ActiveForm
    success_url = reverse_lazy('client20:account_active_done')
    template_name = 'portal/account/active_done.html'

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        assert 'uidb64' in kwargs and 'token' in kwargs

        self.user = self.get_user(kwargs['uidb64'])

        if self.user is not None:
            token = kwargs['token']
            if token == INTERNAL_ACTIVE_URL_TOKEN:
                # active account
                session_token = self.request.session.get(INTERNAL_ACTIVE_SESSION_TOKEN)
                if self.token_generator.check_token(self.user, session_token):
                    # If the token is valid, active account
                    self.valid_link = True
                    return super().dispatch(request, *args, **kwargs)
            else:
                # save token in session, and redirect to account-active
                if self.token_generator.check_token(self.user, token):
                    self.request.session[INTERNAL_ACTIVE_SESSION_TOKEN] = token
                    redirect_url = self.request.path.replace(token, INTERNAL_ACTIVE_URL_TOKEN)
                    return HttpResponseRedirect(redirect_url)
        else:
            raise Http404
        return self.render_to_response(self.get_context_data())

    def get(self, request, *args, **kwargs):
        # treat the active link as a post request
        return self.post(request, *args, **kwargs)

    def form_valid(self, form):
        # form is always valid
        # change is_active to True
        form.save()
        del self.request.session[INTERNAL_ACTIVE_SESSION_TOKEN]
        return self.render_to_response(self.get_context_data())

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(**self.get_form_kwargs(), data={'user_pk': self.user.pk})

    @staticmethod
    def get_user(uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
            user = None
        return user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.valid_link:
            context['valid_link'] = True
        else:
            context.update({
                'form': None,
                'valid_link': False,
            })
        return context


class PasswordRecover(auth_views.PasswordResetView):
    """
    密码找回页面，填写邮箱
    """
    title = '密码找回'
    form_class = PasswordResetForm
    # from_email = settings.DEFAULT_FROM_EMAIL
    email_template_name = 'portal/account/password/reset_email.html'
    html_email_template_name = 'mail/general.html'
    success_url = reverse_lazy('portal:account_password_recover_done')
    template_name = 'portal/account/password/recover.html'
    subject_template_name = 'portal/account/password/reset_subject.txt'

    def form_valid(self, form):
        self.extra_email_context = {
            'host': self.request.META['HTTP_HOST'],  # fixme
            'date': timezone.now().strftime('%Y-%m-%d')}
        return super().form_valid(form)


class PasswordResetConfirm(auth_views.PasswordResetConfirmView):
    """
    用户通过正确的链接进入密码重置页面
    """
    form_class = SetPasswordForm
    template_name = 'portal/account/password/reset_confirm.html'
    success_url = reverse_lazy('portal:account_password_reset_confirm_done')

sandbook/portal/views/novel.py
from django.views.generic import CreateView, DetailView, ListView

from base.models import Novel, Chapter, NovelComment, NovelCommentReply
from general.forms.mixin import FormValidationMixin
from general.views.mixin import LoginRequiredMixin
from portal.forms.author import NovelCommentCreateForm


class NovelDetail(DetailView):
    model = Novel
    pk_url_kwarg = 'novel_id'
    template_name = 'portal/novel/detail.html'
    context_object_name = 'novel'


class NovelChapterDetail(DetailView):
    model = Chapter
    pk_url_kwarg = 'chapter_id'
    template_name = 'portal/novel/chapter_detail.html'
    context_object_name = 'chapter'


class NovelCommentList(ListView):
    """
    整个评论列表，分页
    """
    model = NovelComment
    template_name = 'portal/novel/blocks/comment_area.html'
    paginate_by = 5
    ordering = ('-created_at',)

    def get_queryset(self):
        self.novel = Novel.objects.get(id=self.kwargs['novel_id'])
        novel_comments = self.novel.comments
        self.comment_count = novel_comments.count()
        return novel_comments.order_by(*self.ordering)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context.update(novel=self.novel, comment_counts=self.comment_count)
        return context


class NovelCommentCreate(LoginRequiredMixin, FormValidationMixin, CreateView):
    model = NovelComment
    form_class = NovelCommentCreateForm
    pk_url_kwarg = 'novel_id'
    template_name = 'portal/novel/blocks/comment_area.html'
    # context_object_name = 'novel'

    def form_valid(self, form):
        novel = Novel.objects.get(id=self.kwargs['novel_id'])
        form.instance.novel = novel
        form.instance.user = self.request.user
        form.save()
        return self.render_to_response({'novel': novel})


class NovelCommentReplyList(ListView):
    """
    评论的回复列表，分页
    """
    model = NovelCommentReply
    template_name = 'portal/novel/blocks/comment_reply_area.html'
    paginate_by = 5
    ordering = ('-created_at',)
    context_object_name = 'replies'

    def get_queryset(self):
        self.comment = NovelComment.objects.get(id=self.kwargs['pk'])
        replies = self.comment.replies
        return replies.order_by(*self.ordering)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context.update(comment=self.comment)
        return context


class NovelCommentReplyCreate(LoginRequiredMixin, FormValidationMixin, CreateView):
    """
    创建评论的回复
    """
    model = NovelCommentReply
    fields = ('content',)
    template_name = 'portal/novel/blocks/comment_reply_area.html'
    # context_object_name = 'novel'

    def form_valid(self, form):
        comment = NovelComment.objects.get(id=self.kwargs['pk'])
        form.instance.comment = comment
        form.instance.user = self.request.user
        form.save()
        return self.render_to_response({'comment': comment})

sandbook/portal/templates/portal/novel/detail.html
{% extends 'portal/novel/layout.html' %}
{% load static %}
{% load common_tags novel_tags %}
{% block css %}
  <style>
  .blur-wrap {
    z-index: -1;
    position: absolute;
    height: 455px;
    width: 100%;
    top: -70px;
    left: 0;
    -webkit-transform: translate3d(0,0,0);
    transform: translate3d(0,0,0);
    overflow: hidden;
}
  .blur {
    position: absolute;
    width: 110%;
    height: 455px;
    top: 160px;
    left: 50%;
    margin: -200px -55%;
    background-repeat: no-repeat;
    -webkit-filter: blur(40px);
    -moz-filter: blur(40px);
    -ms-filter: blur(40px);
    filter: blur(40px);
    filter: progid:DXImageTransform.Microsoft.Blur(PixelRadius=10, MakeShadow=false);
    background-position: center;
    background-size: cover
}
  .blur:before {
    content: '';
    display: block;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, .3);
    filter: progid:DXImageTransform.Microsoft.Gradient(startColorstr=#48000000, endColorstr=#48000000);
    position: absolute;
    top: 0;
    left: 0;
    z-index: 100;
  }
  #novel-intro {
    color: #fff;
    text-shadow: 1px 1px 3px rgba(0,0,0,.6);
    margin-bottom: 50px;
    padding-top: 40px;
  }
  #novel-intro p {
    margin-bottom: 2px;
  }
  #novel-intro .media-object {
    width: 180px;
  }
  #novel-intro .media-left {
    padding-right: 20px;
  }
  h1 {
    font-size: 28px;
    margin-top: 0;
  }

  #directory h3 {
    padding-bottom: 10px;
    border-bottom: 1px solid #ffffff;
    font-size: 1.6rem;
  }
  
  #directory h3 > small {
    color: #7F8C8D;;
  }

  #comment-area .comment-title {
    margin-top: 15px;
    margin-bottom: 5px;
  }

  #comment-area .media-heading {
    width: 250px;
    {#border-bottom: 1px solid #eee;#}
    {#padding-bottom: 5px;#}
  }
  #comment-area .media .form-group {
    margin-bottom: 10px;
  }
  #comment-area .media-reply-area {
    border-top: 1px solid #eee;
    padding-top: 10px;
    padding-bottom: 10px;
    margin-top: 0;
  }
  #comment-area .media-reply-area .media-footer {
    margin-bottom: 10px;
  }

  </style>
{% endblock %}
{% block page_content %}
    <div class="blur-wrap">
      <div class="blur" style="background-image: url('{{ novel.cover.url }}')">

      </div>
    <div class="clearfix"></div>
    </div>
  <article class="container">
    {% with author_pen_name=novel.author.authorinfo.pen_name %}
    <section id="novel-intro">
      <div class="row">
        <div class="col-lg-12">
          <div class="media">
            <div class="media-left">
              <img class="media-object" src="{{ novel.cover.url }}" alt="《{{ novel.name }}》封面">
            </div>
            <div class="media-body">
              <h1>{{ novel.name }} <small class="ml-5">{{ author_pen_name }} 著</small></h1>
              <div class="mb-3">
                <span class="badge badge-primary">{{ novel.category.name }}</span>
                <span class="badge badge-info">{{ novel.sub_category.name }}</span>
              </div>
              <p>更新于：{{ novel.updated_at|render_datetime }}</p>
              <p>收藏：0</p>
              <p>点击：0</p>
              <p>评论：0</p>
              <p class="mt-4">
                <button class="btn btn-primary btn-sm mr-2">立即试读</button>
                <button class="btn btn-info btn-sm">加入书架</button>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section id="novel-main">
      <div class="row">
        <div class="col-md-9 col-lg-9" id="left-part">

          {# 作品信息 #}
          <section>
            <div class="panel" id="summary">
              <div class="panel-heading"><h2 class="h3 m-0">作品信息</h2></div>
              <div class="panel-body"><p>
                {{ novel.intro|safe }}</p>
              </div>
            </div>
          </section>

          {# 作品目录 #}
          <section>
            <div class="panel" id="directory">
              <div class="panel-heading"><h2 class="h3 m-0">目录</h2></div>
              <div class="panel-body">
                {% for volume in novel.volume_set.all %}
                  <div class="row mb-5 mx-0">
                    <h3 class="mb-4 m-0">{{ volume.name }}, 共{{ volume.chapter_set.count }}章
                      <small class="text-secondary ml-2"> 本卷共 {{ volume|volume_word_count|default_if_none:0 }} 字</small>
                    </h3>
                    {% for chapter in volume.chapter_set.all %}
                      <div class="col col-xs-6 col-md-6 col-lg-4 text-left mb-4 pl-0">
                        <a class="text-dark" href="{% url 'portal:novel_chapter_detail' chapter.id %}">{{ chapter.title }}</a>
                      </div>
                    {% endfor %}
                  </div>
                {% endfor %}
                <p>
                </p>
              </div>
            </div>
          </section>

          {# 作品评论 #}
        <section>
          <div class="panel" id="comment-area">
              <div class="panel-heading"><h2 class="h3 m-0">评论 (-)</h2></div>
              <div class="panel-body">
                <div class="ui fluid placeholder ml-4 mt-4 mb-5">
                <div class="image header">
                  <div class="line"></div>
                  <div class="line"></div>
                </div>
                <div class="paragraph">
                  <div class="line"></div>
                  <div class="line"></div>
                  <div class="line"></div>
                  <div class="line"></div>
                  <div class="line"></div>
                </div>
              </div>
              </div>
          </div>
        </section>

        </div>


        <div class="col-md-3 col-lg-3 hidden-xs hidden-sm" id="right-part">
          <aside>
            <div class="panel" id="author-works">
              <div class="panel-heading"><h2 class="h3 m-0">{{ author_pen_name }}的其他作品</h2></div>
              <div class="panel-body">
              </div>
            </div>
        </aside>
        </div>

      </div>
    </section>
  {% endwith %}
  </article>
{% endblock %}
{% block js %}
  <script>
    $(function () {
      let NovelDetail = {
        urls: {
          commentList: '{% url 'portal:novel_comment_list' novel.id %}',
          replyList: '{% url 'portal:novel_comment_reply_list' 0 %}'
        },
        init: function () {
          return this.bindUIActions(), this
        },
        bindUIActions: function () {
          this.loadComments();
          this.bindReplyBtn();

          // this.handleForm();
        },
        bindReplyBtn: function () {
          let self = this;
          $('[data-comment-reply-btn]').unbind('click').click(function () {
            let $this = $(this), commentId = $this.attr('data-comment-reply-btn');
            let $replyArea = $this.parent().parent().find('.media-reply-area');
            if ($replyArea.is(':visible')) {
              $replyArea.hide().html('');
            } else {
              self.loadReplies('', commentId, $this)
            }
          })
        },
        loadComments: function (page) {
          console.log('loadComments init')
          let self = this;
          page = page || '';
          $.ajax({
            url: this.urls.commentList + '?page={0}'.format(page),
            success: function (res) {
              $('#comment-area').replaceWith(res);
              console.log('loadComments loaded')

              // bind post form
              let $commentPostForm = $('#comment-post-form');
              let $validator = Portal.validateForm($commentPostForm);
              $commentPostForm.submit(function (e) {
                console.log('bindCommentPostForm submit')
                let $this = $(this);
                e.preventDefault();
                {#let $validator = $this.validate();#}
                if ($validator.form()) {
                  $.ajax({
                    url: $this.attr('action'),
                    data: $this.serialize(),
                    type: $this.attr('method'),
                    success: function (res) {
                      console.log('bindCommentPostForm success')
                      self.loadComments();
                    }
                  })
                }
              });

              // bind reply btn
              self.bindReplyBtn();

              // login check
              self.bindLoginCheck();

              // bind pagination click
              $('.pagination-area').find('a').click(function (e) {
                e.preventDefault();
                self.loadComments($(this).attr('data-page'))
              })
            }
          })
        },
        loadReplies: function (page, commentId, $replyBtn) {
          console.log('loadReplies')
          let self = this;
          page = page || '';
          $.ajax({
            url: self.urls.replyList.replace('0', commentId) + '?page={0}'.format(page),
            success: function (res) {
              // render
              $replyBtn.parent().parent().find('.media-reply-area').replaceWith(res);

              // bind login check
              self.bindLoginCheck();

              let $replyArea = $replyBtn.parent().parent().find('.media-reply-area');
              $replyArea.show();
              $replyArea.find('textarea').focus();

              // validate
              let $replyForm = $replyArea.find('form');
              let $validator = Portal.validateForm($replyForm);
              $replyForm.submit(function (e) {
                e.preventDefault();
                if ($validator.form()) {
                  $.ajax({
                    url: $replyForm.attr('action'),
                    data: $replyForm.serialize(),
                    type: $replyForm.attr('method'),
                    success: function (res) {
                      self.loadReplies(1, commentId, $replyBtn);
                      let replyCount = $replyBtn.parent().parent().find('.media-reply-area').attr('data-reply-count');
                      $replyBtn.text('回复({0})'.format(parseInt(replyCount) + 1));

                      $replyBtn.parent().parent().find('.media-reply-area').show()
                    }
                  })
                }
              });
              $('.reply-pagination-area').find('a').click(function (e) {
                e.preventDefault();
                self.loadReplies($(this).attr('data-page'), commentId, $replyBtn)
              });

            }
          });
        },
        bindLoginCheck: function () {
          console.log('bindLoginCheck')
          $('#comment-area').find('[name]').unbind('focus').focus(function () {
            $.ajax({
              url: Portal.urls.isLogin,
              success: function (res) {
                if (!res.result) {
                  Portal.$loginModal.modal();
                  Portal.$loginModal.on('shown.bs.modal', function () {
                    $(this).find('input[name=username]').focus()
                  })
                }
              }
            })
          })
        }
      }.init();
    })
  </script>
{% endblock %}

sandbook/portal/templates/portal/novel/layout.html
{% extends 'portal/layout.html' %}
{% block title_content %}《{{ novel.name }}》 - {{ novel.author.username }}{% endblock %}